big change

diff --git a/.github/workflows/BuildPushPUblish.yml b/.github/workflows/BuildPushPUblish.yml
--- a/.github/workflows/BuildPushPUblish.yml
+++ b/.github/workflows/BuildPushPUblish.yml
@@ -44,14 +44,28 @@ jobs:
         application_id: ${{ secrets.GH_APP_ID }}
         application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
 
+    - name: Log in to Container Registry
+      uses: docker/login-action@v3
+      with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v3
+
+    - name: Set IMAGE_TAG variable
+      run: |
+        IMAGE_TAG=$(echo "${{ inputs.image_name }}:${{ github.sha }}" | tr '[:upper:]' '[:lower:]')
+        echo $IMAGE_TAG
+        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
+
+    - name: Build Docker image
+      run: docker build -t $IMAGE_TAG -f ${{ inputs.dockerfile_path }} .
+
     - name: Build and push Docker image to GHCR
       run: |
-        IMAGE_TAG=$(echo "ghcr.io/${{ github.repository }}/api:${{ github.sha }}" | tr '[:upper:]' '[:lower:]')
-        echo $IMAGE_TAG
-        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
-        docker build -t $IMAGE_TAG -f src/Message/Dockerfile .
         docker push $IMAGE_TAG
-        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
 
     - name: Check if Azure Container App exists
       id: check_aca
@@ -63,9 +77,18 @@ jobs:
         fi
 
     - name: Validate token access to GHCR
+      id: validate_ghcr
       run: |
+        set -e
         curl -v -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
         https://ghcr.io/v2/acmetickets/eventmanagement/api/tags/list
+
+    # Abort workflow if GHCR validation fails
+    - name: Abort if GHCR validation failed
+      if: failure() && steps.validate_ghcr.outcome == 'failure'
+      run: |
+        echo "GHCR token validation failed. Aborting workflow."
+        exit 1
 
     - name: Create Container App (if not exists)
       if: steps.check_aca.outputs.exists == 'false'
